wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.12
    session_history: code/_session_history.ipynb
    start_time: 1645478382
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 2
      4: 3.7.12
      5: 0.12.10
      8:
      - 1
      - 2
      - 5
